name: Commit Lint

on:
    push:
        branches: [main, dev]

jobs:
    commitlint:
        name: Validate Commit Message
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Validate latest commit (dev branch - squash merge)
              if: github.ref == 'refs/heads/dev'
              run: npx commitlint --from HEAD~1 --to HEAD --verbose

            - name: Validate new commits (main branch - rebase merge)
              if: github.ref == 'refs/heads/main'
              run: npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
